# Generated by Django 2.1.7 on 2019-03-27 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XiciModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='服务器地址')),
                ('ip_address', models.CharField(max_length=200, verbose_name='IP地址')),
                ('ip_type', models.CharField(max_length=200, verbose_name='IP类型')),
                ('ip_speed', models.CharField(max_length=200, verbose_name='IP速度')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '免费代理IP',
                'verbose_name_plural': '免费代理IP',
            },
        ),
    ]
